### ISSUE TITLE
Deprecate included config files

### ISSUE THREAD

**Issue by WouterJ** [symfony-cmf/Testing#115]
Currently, Testing includes lots of config files. I think it's best to remove all included configuration apart from `framework.secret` (which is the minimal config requried to get the AppKernel running with FrameworkBundle).

A bundle then needs to include its own config, allowing them to configure it exactly to fit their needs. This also avoids things like #113.

/cc @dantleech @lsmith77 @dbu Let's make a decision about this soon, so we can trigger deprecation notices in 1.3 (which will be released very soon).

**Comment by lsmith77** [comment]
+1 from me .. so we would only remove them in 2.0?

**Comment by dantleech** [comment]
The original idea was to reduce duplication - originally the CMF bundles all duplicated the same config files and made maintainance a pain. If we made this change and were again duplicating lots of config files then I think that would be bad, but I also know that the current situation is far from ideal - lets do this and see how it goes.

**Comment by WouterJ** [comment]
@dantleech the config files haven't changed much since Testing 1.0. I think it is a bit more difficult during a refactoring, but this was especially an important reason *before* 1.0.

Btw, we might ever create a tool to update files in all repositories. We're facing the same problem with the travis config files for instance.
