### ISSUE TITLE
Symfony 4.1 support

### ISSUE THREAD

**Issue by chirimoya** [symfony-cmf/testing#179]
PHP Fatal error:  Cannot redeclare static `Symfony\Bundle\FrameworkBundle\Test\WebTestCase::$container` as non static `Symfony\Cmf\Component\Testing\Functional\BaseTestCase::$container` in .../phpcr-migrations-bundle/vendor/symfony-cmf/testing/src/Functional/BaseTestCase.php on line 27

https://github.com/symfony-cmf/testing/blob/dd8d71d62e7b5cf4f3e46af4ba0fe3ee2dd2decc/src/Functional/BaseTestCase.php#L39

https://github.com/symfony/framework-bundle/blob/39156eb4298d4cc28f6d5d23af10fb2f246e5529/Test/KernelTestCase.php#L36

https://travis-ci.org/dantleech/phpcr-migrations-bundle/jobs/387870194#L556

**Comment by dbu** [comment]
fixed in 2.1
