### ISSUE TITLE
Remove coupling to the kernel environment, use ENV variables

### ISSUE THREAD

**Issue by dantleech** [symfony-cmf/testing#82]
Currently we decide which configuration to use based on the kernel environment, i.e. either `phpcr` or `orm`.

In hindsight I do not think this was a good idea.
- It implies that we only ever have variations for the PHPCR persistence layer.
- It breaks applciations that depend on the value of the kernel enviornment for other reasons.

For example in SuluCMF we are doing the following:

``` php
// ../TestBundle/Resources/config.php
<?php

$kernelRootDir = $container->getParameter('kernel.root_dir');
$bundleName = null;

$phpcr = getenv('SULU_PHPCR');
$phpcr = $phpcr ? : 'jackrabbit';
$orm = getenv('SULU_ORM');
$orm = $orm ? : 'mysql';

$loader->import('sulu.yml');
$loader->import('phpcr_' . $phpcr . '.yml');
$loader->import('orm_' . $orm . '.yml');
```

**Comment by ElectricMaxxx** [comment]
This issue was its time in front :-)
